### PR TITLE
Automatically send slack messages

### LINKED ISSUE #99: Add slack notifications for commonly forgotten user tasks
The release manager should be notified for at least some tasks, for example the initial code freeze reminder task, since they are easy to forget.

### PR DESCRIPTION
**Pull request by remcowesterhoud**
Send a message for:
- Code freeze (send in #ask-zeebe)
- Notify other teams about release (send in #c8-release-announcements)
- Daily reminders if the release is still in progress (send in #ask-zeebe, tagging the release manager)

Slack messages are send using the new Slack connector. The messages will be send through Zeebot. In order to tag the release manager a decision table needed to be added. This will take the release manager as input and give the slack id as output.

I've also had to add a `current_release_manager` variable to the `zeebe_release` process. The reason for this is that the `release_manager` variable could already be updated with the next release manager before the process is finished. Since we don't want to tag the next release manager we have to keep track of the current release manager.

In order to fix the test so support deploying of DMN I needed an updated EZE version. Since this one is not available on maven central yet, I decided to migrate the tests to ZPT.

closes zeebe-io/zeebe-releaser#99 zeebe-io/zeebe-medic-process#221

### CODE REVIEW

**Comment by remcowesterhoud** [comment]
@oleschoenburg I feel like this PR will solve the issue you've created by sending daily reminder if the release process is still running. Please let me know if you had something else in mind 🙂

**Comment by remcowesterhoud** [comment]
To see the process in the desktop modeler you'll need to add the element templates of the connectors manually. See here how to do this:
[https://github.com/camunda/web-modeler/tree/01f6cf5b2c406cbe588095e681d1478bde87fb[…]BpmnJSExtensions/connectorsExtension/.camunda/element-templates](https://github.com/camunda/web-modeler/tree/01f6cf5b2c406cbe588095e681d1478bde87fbf2/webapp/src/App/Pages/Diagram/BpmnJSExtensions/connectorsExtension/.camunda/element-templates)
[3:45](https://camunda.slack.com/archives/D02DDUQNPDF/p1658151919745269)
https://docs.camunda.io/docs/components/modeler/desktop-modeler/element-templates/configuring-templates/

**Review by lenaschoenburg — COMMENTED** [review]
Nice, this is going to be great :rocket:

Model looks mostly good to me :+1: 

:wrench: I'd suggest to not pass in the slack id as input for the zeebe_release process. That way when we update the `current_release_manager`, slack notifications are sent to the right person. 

:wrench: : the post_release process should also be called with `current_release_manager`. It's not used right now but it will surprises in the future.

**Comment by remcowesterhoud** [comment]
> 🔧 : the post_release process should also be called with current_release_manager. It's not used right now but it will surprises in the future.

I'm not sure what you mean here. The post release process does not have any input variables. It does have a `release_manager` output variable, which gets populated by the next release manager. We shouldn't change this one.


Also I've fixed the tests. It's become a bit of a larger change because there was no EZE version on maven central. Because of this I migrated it to ZPT, which is an improvement anyways in my opinion. Let me know if you thing the PR is too large now, then I will split it up in separate PRs.

**Review by lenaschoenburg — APPROVED** [review]
Thanks @remcowesterhoud :+1: 

> I'm not sure what you mean here. The post release process does not have any input variables.

Yeah it's fine, this would just be for future extension. Let's merge this as is :rocket:

**Comment by remcowesterhoud** [comment]
bors merge

**Pull request merged**
