### PR TITLE
Improve release process

### PR DESCRIPTION
**Pull request by Zelldon**
Due to my recent experience in doing patch releases I had some big pain I wanted to use that to resolve some issues.

I'm very sorry that this PR is so big and has so many changes, but unfortunately I found no better way since the xml is generated by the modeler it would lead to enormous merge conflicts if I would do it in separate PR's so please dont hate me.

What the PR contains:

--------------------
### Forms everywhere

I added to all forms at the top a reference to the current release, to get some consistency. We already had some which contained it and I really like it, but not all had this. It is quite confusing if you run multiple releases and don't know where the task belongs to.

Looks like this:

changelog
getting-started

------------------

### Form for github labels

Furthermore I introduce a new form for the github release labels task, because I was not sure when reaching this task what to do here.

labels

----------------

### Patch release QA

For the QA process I made some changes, since the patch release QA is quite simple I extracted the parts which are necessary. This allows us after merging and if you accept it to simplify the other task contents, which always mentioned patch releases. It makes it also simpler to follow a patch release in operate.

patch-qa

Previously:

current-qa

------------

### Refactor release process

Add some condition to not execute tasks which are not needed

zeebe_release

Previously:

current-release

### Refactor Post release

Here as well I did some refactoring and clean up. I removed some tasks which were not necessary or duplicated, e.g. Task to copy changelog, merge to master or notify the teams a second time. Furthermore added some condition to not execute task which are not necessary for patch releases.

post_release

Previously:

current-post

### Feedback

Please let me know what you think. If you would accept it I will fix the tests.

**Please keep in mind we should deploy the processes after merging. Brings me to: we need auto deploy...**

### CODE REVIEW

**Comment by korthout** [comment]
@Zelldon 👍 I've looked at the changes to the processes, and they make sense to me. 

The only change I'm not sure about is extracting the patch-qa. Making changes to the QA process would now have to be duplicated which may be forgotten. Perhaps we can extract it instead using a call-activity in the main QA process to the (what is now called) patch QA process. I'd then also rename it to CI-QA process or something like that.

**Comment by Zelldon** [comment]
> The only change I'm not sure about is extracting the patch-qa. Making changes to the QA process would now have to be duplicated which may be forgotten. Perhaps we can extract it instead using a call-activity in the main QA process to the (what is now called) patch QA process. I'd then also rename it to CI-QA process or something like that.

I totally agree with this. I think it makes it even worse as you said since we have the duplication of the forms here. I removed the new process and just added an xor to the qa process to skip the tasks we don't need.

Looks like this now:


zeebe_release

**Review by oleschoenburg — APPROVED** [review]
Thank you so much @Zelldon, this looks really good and addresses some pain points I had when I was release manager. I tested the process for patch releases manually, looks all good :)

**Comment by Zelldon** [comment]
just realized that we already have auto deployment :muscle: nice work @oleschoenburg

**Pull request merged**
