### PR TITLE
Release 1.1.0 improvements

### PR DESCRIPTION
**Pull request by korthout**
I've collected some improvements that I came across while releasing version 1.1.0.

Most notably, 
- adding additional help messages
- adding message catch event notes for message name and correlation key
- making it more clear that a release **candidate** should be build
- adding links to blog posts folders

Easiest to review on commit basis

### CODE REVIEW

**Comment by korthout** [comment]
@saig0 Please have a look when you have time for it :)

**Comment by Zelldon** [comment]
Sorry @korthout 😅

**Comment by Zelldon** [comment]
Had no time yet🙈

**Comment by korthout** [comment]
@Zelldon No problemo, I already had such an idea

**Comment by saig0** [comment]
I'll have a look :+1: But you need to wait until end of next week :sweat_smile:

**Review by saig0 — APPROVED** [review]
I like the additions to the process :+1: 

Everything looks good so far I can tell without running the process :sweat_smile:

**Pull request merged**
