### PR TITLE
Clean up the repository

### PR DESCRIPTION
**Pull request by korthout**
This adds a bunch of small improvements:
- moves processes from `src/test/resources` to `src/main/resources`
- adds spotless and enables `ktfmt` and `sortpom`, checking the format in CI, while auto applying it locally
- cleans up the README, explaining a bit more how this project works
- removes an unused shell script
- fixes the `Send message to Recreate Benchmark` in QA process

### CODE REVIEW

**Comment by korthout** [comment]
@saig0 Seems I forgot to ask for a review on this 😮 Can you have a look? Should be easy to review as individual commits.

**Review by saig0 — APPROVED** [review]
@korthout looks good :+1:

**Comment by korthout** [comment]
bors merge

**Comment by korthout** [comment]
Seems that bors is confused... 😕 

It says its running, but it didn't push any merge commit yet

**Comment by korthout** [comment]
bors cancel

**Comment by korthout** [comment]
bors try

**Comment by korthout** [comment]
bors try

**Comment by korthout** [comment]
bors merge

**Comment by korthout** [comment]
Seems to run now. Not sure why it didn't before. 🤷

**Pull request merged**
