### PR TITLE
refactor: add nikola to release process

### LINKED ISSUE #130: Add Nikola to the release process
Nikola should be added to the release processes so he can join the release rotation

- Add Nikola to the `release_collect_data.form` and update the collect data tasks in `zeebe_release_orchestrator.bpmn` and `post_release.bpmn`.
- Add Nikola's slack id to the `get_slack_id.dmn`

When this is done deploy the files to the Zeebe Cluster.

### PR DESCRIPTION
**Pull request by koevskinikola**
As part of my onboarding for the Zeebe Process Automation team, add myself to the Zeebe release process.

closes #130

### CODE REVIEW

**Review by remcowesterhoud — APPROVED** [review]
LGTM 🚀

**Comment by remcowesterhoud** [comment]
@koevskinikola Do you want to deploy the process to the cluster yourself?

**Comment by remcowesterhoud** [comment]
Oh actually this is automated these days 😄 Though the workflow is broken but that most likely has to do with the cluster change.

**Comment by koevskinikola** [comment]
> @koevskinikola Do you want to deploy the process to the cluster yourself?

I actually wanted to ask you about that, but since it's automated I guess it's not necessary.

**Pull request merged**
